services:

  library_app:
    image: library_app
    container_name: library_app
    ports: 
      - 5237:8080

  library_api:
    image: library_api
    container_name: library_api
    ports: 
      - 5091:8080

  library_database:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: library_database
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=SQLserver123!
    ports: 
      - 1433:1433
